/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zooms;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author cesar
 */
public class ImageForm extends javax.swing.JFrame {
String Path;
    /**
     * Creates new form ImageForm
     */
    public ImageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jL_imagen = new javax.swing.JLabel();
        JtextImg = new javax.swing.JTextField();
        BTBuscar = new javax.swing.JButton();
        zoomMas = new javax.swing.JButton();
        zoomMenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jL_imagen);

        JtextImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtextImgActionPerformed(evt);
            }
        });

        BTBuscar.setText("Buscar");
        BTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuscarActionPerformed(evt);
            }
        });

        zoomMas.setText("+");
        zoomMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomMasActionPerformed(evt);
            }
        });

        zoomMenos.setText("-");
        zoomMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(BTBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtextImg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zoomMas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(zoomMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zoomMas)
                    .addComponent(zoomMenos))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JtextImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTBuscar)
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtextImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtextImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtextImgActionPerformed

    private void BTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuscarActionPerformed
        try {
            JFileChooser flchoos = new JFileChooser(System.getProperty("user.home"));
            flchoos.setFileSelectionMode(JFileChooser.FILES_ONLY);
            flchoos.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp","jpg","png","bmp"));
            if(flchoos.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = flchoos.getSelectedFile();
            Image imagen = ImageIO.read(file);
            ImageIcon Icon=new ImageIcon(imagen);
            jL_imagen.setIcon(Icon);
            Path = file.getAbsolutePath();
            }else{
                
            }
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(ImageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTBuscarActionPerformed
private Image ZoomImage(int w, int h, Image imagen){
    BufferedImage buf= new BufferedImage( w, h,BufferedImage.TYPE_INT_RGB);
    Graphics2D qrf = buf.createGraphics();
    qrf.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    qrf.drawImage(imagen,0,0,w,h,null);
    qrf.dispose();
    return buf;
}
    
    private void zoomMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomMenosActionPerformed
try{
        int w= jL_imagen.getWidth();
        int h= jL_imagen.getHeight();
        File file= new File(Path);
        Image imagen = ImageIO.read(file);
        ImageIcon Icon = new ImageIcon(ZoomImage(w-100, h-100, imagen)); 
        jL_imagen.setIcon(Icon);
}catch(Exception e){   
}
// TODO add your handling code here:
    }//GEN-LAST:event_zoomMenosActionPerformed

    private void zoomMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomMasActionPerformed
try{
        int w= jL_imagen.getWidth();
        int h= jL_imagen.getHeight();
        File file= new File(Path);
        Image imagen = ImageIO.read(file);
        ImageIcon Icon = new ImageIcon(ZoomImage(w+100, h+100, imagen)); 
        jL_imagen.setIcon(Icon);
}catch(Exception e){   
}
// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_zoomMasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBuscar;
    private javax.swing.JTextField JtextImg;
    private javax.swing.JLabel jL_imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton zoomMas;
    private javax.swing.JButton zoomMenos;
    // End of variables declaration//GEN-END:variables
}
